name: Build APK
on: push
jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          npm install -g @bubblewrap/cli
          # Ito ang manual setup para hindi na mag-error sa prompts
          bubblewrap init --manifest=manifest.json --out=./ --confirmResName --confirmSmallIcon
          
          # Bubuo tayo ng dummy android project structure
          bubblewrap build --skipSigning
        continue-on-error: true

      - name: Force Search APK
        run: |
          # Hahanapin natin kung nasaan napunta yung file at ililipat sa root
          find . -name "*.apk" -exec cp {} ./reader.apk \;
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Reader-APK
          path: reader.apk
