name: Build APK
on: push
jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Bubblewrap
        run: |
          npm install -g @bubblewrap/cli
          # Gagamit tayo ng yes command para i-auto-accept lahat ng prompts
          yes | bubblewrap init --manifest=manifest.json --out=./
          yes | bubblewrap build --skipSigning
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Reader-APK
          path: "*.apk" # Pakitanggal yung ./ para mas malawak ang search
